spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
jwt:
  secret: ThisIsALongEnoughJwtSecretForTests_AtLeast32Chars!!
  access-token-validity-ms: 900000
  refresh-token-validity-ms: 1209600000