spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:project_a_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  port: 0

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  secret: test-test-test-test-test-test-test-test-32b
  access-validity-ms: 60000      # 1분
  refresh-validity-ms: 300000    # 5분

app:
  verify:
    base-url: http://localhost

logging:
  level:
    root: warn
    org.springframework.web: info
    org.hibernate.SQL: debug