# src/main/resources/application-dev.yml
# 개발 환경 DB 설정 (MySQL 기준)
spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}                           # jdbc:mysql://localhost:3306/yourdb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false                      # 권장: 컨트롤러에서 지연로딩 이슈 줄이기
    hibernate:
      ddl-auto: update                       # 개발 편의용 (운영은 Flyway/Liquibase 권장)
    properties:
      hibernate:
        format_sql: true

  # H2 콘솔을 쓰지 않으면 false 권장 (SecurityConfig에서 이 값으로 허용여부 결정)
  h2:
    console:
      enabled: false

  # (선택) 문제세부 응답 포맷
  mvc:
    problemdetails:
      enabled: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# 서버 에러 응답에 메시지/바인딩오류 노출 (개발용)
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param    # URL에 ?trace=true 붙이면 스택 보임

# 로그 레벨 (개발 가시성)
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    com.ll.P_A: DEBUG

# Swagger / OpenAPI 문서
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    enabled: true
    path: /v3/api-docs

# Actuator 노출 (헬스체크 등)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# JWT 토큰 설정
jwt:
  secret: ${JWT_SECRET}                      # 운영은 반드시 시크릿을 안전하게 주입
  access-token-validity-ms: 900000           # 15분
  refresh-token-validity-ms: 1209600000      # 14일

# 메일 발송 계정
mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

# Redis (Refresh 토큰 저장 용도)
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT:6379}

# 이메일 인증 링크 베이스 URL
app:
  verify:
    base-url: ${APP_VERIFY_BASE_URL}