# 운영 환경 DB 설정 (보통 실제 MySQL 사용)
spring:
  datasource:
    url: ${DB_URL} # 운영 DB 접속 URL
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver} # MySQL 드라이버
    username: ${DB_USERNAME} # 운영 DB 사용자명
    password: ${DB_PASSWORD} # 운영 DB 비밀번호

# JWT 토큰 설정 (운영에서는 환경변수로 반드시 세팅)
jwt:
  secret: ${JWT_SECRET} # JWT 시크릿키
  access-token-validity-ms: ${ACCESS_TTL_MS:900000} # Access Token TTL (기본 15분)
  refresh-token-validity-ms: ${REFRESH_TTL_MS:1209600000} # Refresh Token TTL (기본 14일)

# 메일 발송 계정
mail:
  username: ${MAIL_USERNAME} # 메일 아이디
  password: ${MAIL_PASSWORD} # 메일 비번

# Redis 접속 정보
redis:
  host: ${REDIS_HOST} # Redis 호스트
  port: ${REDIS_PORT} # Redis 포트
  password: ${REDIS_PASSWORD:} # Redis 비밀번호 (없으면 빈값)

# 운영 환경 모니터링 엔드포인트 노출 (health, info)
management:
  endpoints:
    web:
      exposure:
        include: health,info