spring:
  config:
    activate:
      on-profile: dev

# 개발에서만 문서 활성화
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 로컬 개발 편의 로깅(원하면 조절)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# 로컬 개발 기본값(원하면 주석 해제해서 직접 값 지정 가능)
# server:
#   port: 8080
# app:
#   verify:
#     base-url: http://localhost:8080